version: '2'

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:fpm
    volumes:
      - ./__wordpress:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  db:
    image: mysql
    volumes:
      - ./__db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  nginx:
    image: nginx
    depends_on:
      - wordpress
    ports:
      - "8000:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/crt:/etc/nginx/pki/crt
      - ./ssl/key:/etc/nginx/pki/key
      - ./__wordpress:/var/www/html
    restart: always
