version: '2'

services:
  wordpress:
    depends_on:
      - db
    #image: wordpress
    build: ./docker-image/wordpress-sendmail-and-ssl
    volumes:
      - ./ssl/crt:/etc/ssl/certs/ssl-cert-snakeoil.pem
      - ./ssl/key:/etc/ssl/private/ssl-cert-snakeoil.key
    ports:
      - "8000:443"
      - "8001:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  db:
    image: mysql
    volumes:
      - ./__db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress