version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
      - TAKE_FILE_OWNERSHIP=1
    volumes:
      - ./__elasticsearch_data/:/usr/share/elasticsearch/data/
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:6.2.2
    ports:
      - 5601:5601
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    command: sh -c "exec kibana"

  filebeat_for_osquery_in_container:
    depends_on:
      - elasticsearch
      - kibana
    image: docker.elastic.co/beats/filebeat:6.2.2
    volumes:
      - ./__osquery_results/:/var/log/osquery/:ro
      - ./filebeat_module_osquery.yml:/usr/share/filebeat/modules.d/osquery.yml
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    user: root:filebeat
    command: sh -c "chown root:filebeat filebeat.yml modules.d/osquery.yml; chmod go-w filebeat.yml modules.d/osquery.yml; while ! curl -sSL http://kibana:5601 >/dev/null 2>&1; do echo wait for http://kibana:5601; sleep 1; done; 2>/dev/null; exec filebeat --setup"

  filebeat_for_osquery_in_host:
    depends_on:
      - elasticsearch
      - kibana
    image: docker.elastic.co/beats/filebeat:6.2.2
    volumes:
      - /var/log/:/var/log/:ro   #for /var/log/osquery/osqueryd*.log
      - ./filebeat_module_osquery.yml:/usr/share/filebeat/modules.d/osquery.yml
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    user: root:filebeat
    command: sh -c "chown root:filebeat filebeat.yml modules.d/osquery.yml; chmod go-w filebeat.yml modules.d/osquery.yml; while ! curl -sSL http://kibana:5601 >/dev/null 2>&1; do echo wait for http://kibana:5601; sleep 1; done; 2>/dev/null; exec filebeat --setup"

  metricbeat:
    depends_on:
      - elasticsearch
      - kibana
    image: docker.elastic.co/beats/metricbeat:6.2.2
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
    user: root:metricbeat
    command: sh -c "chown root:metricbeat metricbeat.yml; chmod go-w metricbeat.yml; while ! curl -sSL http://kibana:5601 >/dev/null 2>&1; do echo wait for http://kibana:5601; sleep 1; done; 2>/dev/null; exec metricbeat --setup"

  osquery:
    build: ./docker-osquery
    volumes:
      - ./__osquery_results/:/var/log/osquery/
      - ./osqueryd.conf:/etc/osquery/osquery.conf
    command: osqueryd --verbose
