filebeat.modules:
- module: osquery
  result:
    enabled: true
    var.paths: ["/var/log/osquery/osqueryd.results.log*", "/var/log/osquery/osqueryd.snapshots.log*"]

output.elasticsearch:
  enabled: true
  hosts: ['elasticsearch:9200']
  username: elastic
  password: changeme
  template.overwrite: true
