version: '3'

services:
  stf:
    depends_on:
      - rethinkdb
    image: openstf/stf
    command: stf local --adb-host=host.docker.internal --allow-remote --adb-port=15037
    ports:
      - 7100:7100
      - 7110:7110
      - 7400:7400
    environment:
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015

  rethinkdb:
    image: rethinkdb
    volumes:
      - ./__rethinkdb_data:/data
    command: rethinkdb --bind all --cache-size 1024 --http-port 8090
